### ISSUE TITLE
Port request: tty

### ISSUE THREAD

**Issue by Stonks3141** [Stonks3141/ctp-nix#12]
Port: [catppuccin/tty](https://github.com/catppuccin/tty)
Example: https://git.sr.ht/~stonks3141/nixos-config/tree/main/item/modules/system.nix#L49

We'll have to bring in [catppuccin/palette](https://github.com/catppuccin/palette) to get the hex codes.

**Comment by getchoo** [comment]
couldn't we just make derivation with the contents of `dist/` after [build.sh](https://github.com/catppuccin/tty/blob/main/build.sh)?

**Comment by Stonks3141** [comment]
That shouldn't be necessary, the build script just copies the files from `src/`
to `dist/`. I think a more robust approach than running `sed` on the shellscript
files to get `console.colors` would be to just fetch `palette-porcelain.json`
from catppuccin/palette to get hex codes and manually sync the colors with
catppuccin/tty.

**Comment by Anomalocaridid** [comment]
I am interested in implementing this. Regarding bringing the palette in, would it be a good idea to expose the palette and the palette repo's files as packages or something similar as a flake output? 

My reasoning is that would help with manual theming. Exposing the palette would help for when colors need to be used directly. Exposing the palette repo's files would help in specific cases when having a CSS, SCSS, etc. palette would be handy.
