### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Stonks3141** [Stonks3141/ctp-nix#18]
I would like to have a site similar to https://rycee.gitlab.io/home-manager/options.html that describes available configuration options.

**Comment by getchoo** [comment]
[these](https://git.sr.ht/~rycee/nmd) [seem](https://gitlab.com/rycee/home-manager/-/blob/master/docs/default.nix) relevant

**Comment by Stonks3141** [comment]
Thanks! I'll try to set that up this weekend.

**Comment by getchoo** [comment]
completed in https://github.com/Stonks3141/ctp-nix/pull/39, might be improved on in the future though :p
