### ISSUE TITLE
wrong repo url in readme

### ISSUE THREAD

**Issue by birdmanmandbir** [Stonks3141/ctp-nix#68]
links in readme is `catppuccin/nix`, but it should be `Stonks3141/ctp-nix`?

**Comment by isabelroses** [comment]
> links in readme is `catppuccin/nix`, but it should be `Stonks3141/ctp-nix`?

That is because this is a repo that is going to be transferred to the cappuccin org, see https://github.com/catppuccin/catppuccin/issues/2103 for more info.
